### ISSUE TITLE
Bug: Import of opportunities is currently not setting partner_string.

### ISSUE THREAD

**Issue by stevenabadie** [CodeForFoco/volunteercore#108]
Confirmed from api request this is an issue in the api.

**Comment by Alex-Cannon** [comment]
Could you explain more on what's occurring? Is this what you mean:
GET /api/opportunities
will return ALL opportunities not just, say, 10?

If so, we should fix this, but it's not a huge deal at the moment.

**Comment by stevenabadie** [comment]
Update: the query is working fine from what I can tell. The issue is that the partner_string field is indexed by the search engine and I forgot to add generating the partner_string in the import scripts.
