### ISSUE TITLE
Pipenv requirements currentely requires Postgres setup

### ISSUE THREAD

**Issue by stevenabadie** [CodeForFoco/volunteercore#110]
The psycopg2 package requires having Postgres installed and configured. For some it would be easier to set up and start with Sqlite. There should be a way to all using psycopg2-binary for --dev package install and only require psycopg2 for production.

**Comment by stevenabadie** [comment]
It looks like this isn't quite an easy fix with pipenv as it does not support installing packages only for production: https://github.com/pypa/pipenv/issues/3167 . I'm still digging around for a way to do this so the setup will work for both Sqlite and Postgres but I may just remove psycopg2 and only have it in the heroku-production branch for releases to heroku.

**Comment by Alex-Cannon** [comment]
@stevenabadie it's your call. The build works on my machine right now, so as long as it works, I'm good.

**Comment by Alex-Cannon** [comment]
@stevenabadie if you still want to move forward with this, why don't we just use docker containers to match production as much as possible? It'd be pretty easy to setup.

https://www.docker.com/

**Comment by Alex-Cannon** [comment]
We can do this with docker in #174. Closing this issue.
