### ISSUE TITLE
Make all endpoints protected behind authentication

### ISSUE THREAD

**Issue by stevenabadie** [CodeForFoco/volunteercore#112]
If the app is hosted on a public server, I expect most users would not want the app data publicly available. This will be especially important if we decide to later include volunteer data.

**Comment by stevenabadie** [comment]
As a temporary solution it may be possible to block IPs on heroku, so we could block all IPs but ours and VOA for the MVP testing.

**Comment by Alex-Cannon** [comment]
Once this is implemented, we should create another issue for the front-end to support this. I _think_ most of the routes should be OK with this change, but some may break. Best to test on another branch before merging to master.

**Comment by Alex-Cannon** [comment]
Closed via #132
