### ISSUE TITLE
UI/UX: Remove /partners and /opportunities pages?

### ISSUE THREAD

**Issue by Alex-Cannon** [CodeForFoco/volunteercore#113]
@stevenabadie mentioned we should remove the /dashboard/partners and /dashboard/opportunities pages from the **dashboard** because these pages are already mostly functional in the /opportunities and /partners routes.

My thoughts are it makes more sense to remove the /opportunities and /partners routes and keep the **dashboard** /opportunities and /partner routes.

Here are the steps we need to take to make this happen:
1. Decide if the Dashboard is for ALL users OR soley for the admin
2. Remove the /opportunities and /partners routes we don't want
3. Require Authentication for the GET routes.

**Comment by Alex-Cannon** [comment]
The fastest way to do this is to remove the /opportunities and /partners pages and use the dashboard for everything.

**Comment by stevenabadie** [comment]
My thinking for using the current /opportunities and /partners pages is that those pages are more complete in information and styling for use in searching and selecting an Opportunity. Those pages have more detail than just the names of the Opportunity and Partner as in the dashboard. The single Opportunity view page in the dashboard also appears to have less complete styling:

![Screenshot from 2019-05-29 19-06-47](https://user-images.githubusercontent.com/42226506/58601184-f3babf80-8244-11e9-9c9a-db61a70d6054.png)

**Comment by stevenabadie** [comment]
Forgot to tag #112 as that and this ticket go together.

**Comment by Alex-Cannon** [comment]
I see what you're saying. Alright let's do it your way.
