### ISSUE TITLE
UI/UX: Specify form submit button labels

### ISSUE THREAD

**Issue by stevenabadie** [CodeForFoco/volunteercore#119]
Currently the form submit buttons are labeled as _Submit Query_ I think because this is default when they are not specified a value.

The _Query_ portion may confuse users. Maybe having general _Submit_ or _Save_ in all forms is good. Another option is making the submit button more specific to the form such as _Create Opportunity_ or _Save Opportunity_,

Relevant forms are:
/dashboard/opportunities/add
/dashboard/opportunities/edit/####
/dashboard/partners/add
/dashboard/partners/edit/###
/dashboard/tag_categories/add
/dashboard/tag_categories/edit/##
/dashboard/users/add
/dashboard/users/edit/##

**Comment by Alex-Cannon** [comment]
Thanks for finding this issue. Chrome automatically uses "Submit" for submit buttons. I'll set the value for them.
