### ISSUE TITLE
Security: Use HTTP-Only Cookies, not JWT

### ISSUE THREAD

**Issue by Alex-Cannon** [CodeForFoco/volunteercore#138]
I'm not a security expert. I saw this article and from what I've seen elsewhere, we should use http-only cookies, not JWT. 
[Read This](https://logrocket.com/blog/jwt-authentication-best-practices/)

Currently, we have 1 server that does everything, so there's no need for JWT. If in the future we want to separate the api, we can proxy requests from our client server to our api server.

**This issue should be separated into 2 parts. We can keep it as one for now.**

**Comment by stevenabadie** [comment]
All of the API changes for http-only are completed and in branch `138` here and in my fork.
