### ISSUE TITLE
Bug: Search broken in front end build

### ISSUE THREAD

**Issue by stevenabadie** [CodeForFoco/volunteercore#141]
When using the production build of the front end, locally and on heroku, all of the search forms give 404. The search is fine when using npm start to serve the front end locally FYI. Maybe something in the front end build requirement?

**Comment by stevenabadie** [comment]
Additional info, there is no error in the back end and I can get a good API response using /api/opportunities?search= directly from the API.

**Comment by Alex-Cannon** [comment]
Did a quick fix for opportunities and partners in #147. Pushed to heroku. Tested in production. We need to fix users and tags searching.

**Comment by Alex-Cannon** [comment]
@stevenabadie I believe we fixed this issue? I will close. Let me know if it isn't resolved and we can re-open.
