### ISSUE TITLE
Feature MVP: Enhance search on backend

### ISSUE THREAD

**Issue by Alex-Cannon** [CodeForFoco/volunteercore#155]
This is an MVP feature! Here is what Andrew said about search (8/26/2019):

Hey dudes, me here.  Happy Monday to you.  This build is much better!

Couple larger things though:
1. Now when searching for opportunities it ONLY searches for the tags (passions, skills, people groups), and doesn't incorporate other stuff w/ the opportunity - words in the partner name, words in the vol opp title, location, etc..  Hoping that can be changed.  Searching by a combo of those things ideal.
...

**Comment by stevenabadie** [comment]
This can likely be fixed in the woosh configuration. Right now it is set to use 'or' search. I know changing to 'or' will fix this specific issue. However, it may cause other issues. I'll look into it.

**Comment by Alex-Cannon** [comment]
@stevenabadie I was looking at the woosh docs and it looks like you can "weight" certain fields. For example, an opp with { title: "star" } would rank lower than a opp with { tag: "star" }

**Comment by Alex-Cannon** [comment]
@stevenabadie once we have this done, the project should be useable for VOA

**Comment by Alex-Cannon** [comment]
~@stevenabadie I'm working on this now. I'll try to get it done over the weekend.~

I worked on this for ~2 hours and wasn't able to make much progress. @stevenabadie I need help implementing this. Questions I have:

1. Does production use postgresql and development use sql?
2. [I found an example of using weighted search](https://whoosh.readthedocs.io/en/latest/recipes.html#score-results-based-on-the-position-of-the-matched-term), but the docs didn't do a great job with a full example. Any other docs / tutorials you can point me to?
3. Would you tell me how the search / queries work? Or take me through the `opportunities.py` file the next meetup?

I made a PR for this issue: #181 , but it is incomplete. I created the PR so you could see my progress so far.

**Comment by Alex-Cannon** [comment]
Have another issue for this
