### ISSUE TITLE
Partner list wireframe

### ISSUE THREAD

**Issue by stevenabadie** [CodeForFoco/volunteercore#2]
Wireframe for view of list of partners. The partner model currently only has one field, the name. It could be useful to include in this list opportunity data relevant to each partner. An example would be for each partner, the number of opportunities total and then number of active ones.

**Comment by Alex-Cannon** [comment]
https://codeforfoco.slack.com/files/UH99K34DR/FJ1PAN03F/partners.png

Basic Partner page done.

**Comment by stevenabadie** [comment]
This is completed or tracked in other tickets.
