### ISSUE TITLE
Volunteer opportunity form wireframe

### ISSUE THREAD

**Issue by stevenabadie** [CodeForFoco/volunteercore#3]
Form to enter new and edit existing volunteer opportunities. For model field requirements see ticket #8 .

**Comment by Alex-Cannon** [comment]
I created this wireframe and shared it in slack.

**Comment by Alex-Cannon** [comment]
Here are a few iterations:
A - https://wireframe.cc/Ei0ppe
B - https://wireframe.cc/E0mmGu
C - https://wireframe.cc/Bgjzgh

**Comment by stevenabadie** [comment]
This is completed or in design without a wireframe
