### ISSUE TITLE
Revert back to JWT auth with refresh token and http-only cookie

### ISSUE THREAD

**Issue by stevenabadie** [CodeForFoco/volunteercore#33]
The API token auth is currently vulnerable to CSRF attacks. I attempted to implement this with Flask-JWT-Extended but have not been able to get it working. See more details in:

- https://flask-jwt-extended.readthedocs.io/en/latest/tokens_in_cookies.html
- http://www.redotheweb.com/2015/11/09/api-security.html

**Comment by stevenabadie** [comment]
We could close this one out as CSRF was relevant when I was trying to store the token in a cookie. With it stored in the sessionstorage we are good for CSRF. However, we have traded off with possible XSS vulnerabilities as noted in the redotheweb link above.

**Comment by Alex-Cannon** [comment]
@stevenabadie Yea, XSS is annoying. Another option is to use cookies and make them expire after a few hours. That way JS can't access user credentials. For our MVP, I don't think this'll be a big issue. VOA doesn't have much sensitive data. The most they could do is cause some mayhem (I think?).

**Comment by stevenabadie** [comment]
Closing this as duplicate topic of the newly created ticket #138
