### ISSUE TITLE
Volunteer opportunity wireframe

### ISSUE THREAD

**Issue by stevenabadie** [CodeForFoco/volunteercore#4]
Wire frame for view of single volunteer opportunity. This should include data from all fields defined in the volunteer opportunity model #8 .

**Comment by Alex-Cannon** [comment]
I will finish this real quick.

**Comment by jlikesmakingstuff** [comment]
I think this view should look something like this:

https://www.figma.com/file/btGLTiN4evR5MD0XI65Rkdw7/draft-volunteer-opportunity-detail-view?node-id=3%3A193

![draft volunteer opportunity detail](https://user-images.githubusercontent.com/45578886/56394352-4cce1700-61f4-11e9-9967-152bd80b712e.png)

**Comment by stevenabadie** [comment]
This has already been made in design so going to close this out.
