### ISSUE TITLE
User story: specify opportunity frequency

### ISSUE THREAD

**Issue by stevenabadie** [CodeForFoco/volunteercore#40]
Opportunities need a frequency specification that can allow setting the frequency unit (day, week, month, year) and a frequency modifier (1st, 2nd, 3rd, 4th).

**Comment by Alex-Cannon** [comment]
@stevenabadie I think you added this in the api branch? I do need to do this on the front-end still.

**Comment by Alex-Cannon** [comment]
Working on this now...

**Comment by Alex-Cannon** [comment]
We should close this issue. It is done in my /react branch.
