### ISSUE TITLE
Rename: Rename commitment_length to commitment_length_days

### ISSUE THREAD

**Issue by Alex-Cannon** [CodeForFoco/volunteercore#42]
This is not a big deal, but do we agree that commitment_length is an integer of days?

**Comment by stevenabadie** [comment]
In my notes from last Thursday I had commitment length in months but now that you note days, months seems wrong. I'll contact VOA to confirm.

**Comment by stevenabadie** [comment]
Thinking about this a bit more, maybe we should just remove the commitment length field. If there is a commitment length requirement we assume the user will fill the start and end date. If we find later that the user would like to see the commitment length in number of days we could calculate that from the start and end date. If they don't set a start and end date we assume it is a one-time commitment so commitment length isn't needed. Thoughts?

**Comment by Alex-Cannon** [comment]
@stevenabadie these are my thoughts:

1) **start_date, end_date** are for a **one-time** event.
2) **commitment_length** is the **required** length of the commitment. For example, the food bank may require volunteers to commit to 6 months.
3) These should be separated because a non-profit may accept volunteers for any time, **but require at least 6 months of a commitment**.

**Comment by Alex-Cannon** [comment]
commitment_length was renamed to commitment_length_months. This is merged with master.
