### ISSUE TITLE
Volunteer opportunity list wireframe

### ISSUE THREAD

**Issue by stevenabadie** [CodeForFoco/volunteercore#5]
Wire frame of view of list of volunteer opportunities. This would also include search, sorting, and filtering tools.

**Comment by jlikesmakingstuff** [comment]
This is Jordan. I will work on this issue

**Comment by jlikesmakingstuff** [comment]
This wireframe was created by Steven and can be viewed here:

https://www.figma.com/file/Drx0tkBgI7SQ8ETzVHw0pqSN/Volunteer-Force?node-id=0%3A1

**Comment by stevenabadie** [comment]
This is completed already or in process in design.
