### ISSUE TITLE
Bug: GET /api/users returns 401 unauthorized

### ISSUE THREAD

**Issue by Alex-Cannon** [CodeForFoco/volunteercore#51]
When I GET /api/users as an **admin** from **$ flask auto-setup**, 401 unauthorized is returned.
This behavior is strange because **I'm authorized to POST a user, but not GET users.**

Recreate this bug:
* Setup the app
* $ flask db upgrade
* $ flask auto-setup
* $ flask run
* Login with username: admin, password: password
    * POST /api/token/auth with **Basic btoa(_username_:_password_)**
* GET /api/users
* You should see a 401 unauthorized response in the flask console or your browser console.

[Tested with my /react branch](https://github.com/Alex-Cannon/volunteermatching/tree/react)

**Comment by Alex-Cannon** [comment]
I may add testing client-side to prevent silly mistakes in the future.

**Comment by stevenabadie** [comment]
@Alex-Cannon  I'm not able reproduce this issue using httpie to GET request the /api/auth endpoint. Here is the command history using your /react branch.

```
(volunteermatching-XXXXXXX) [XXXXXX@XXXXX volunteermatching]$ http -a admin:password POST http://127.0.0.1:5000/api/token/auth
HTTP/1.0 200 OK
Content-Length: 50
Content-Type: application/json
Date: Wed, 15 May 2019 01:07:41 GMT
Server: Werkzeug/0.15.2 Python/3.6.8

{
    "token": "aOUfpaYJ7G9z2qVJ+x+cTu9rudU61ulr"
}

(volunteermatching-XXXXXXXX) [XXXXX@XXXXXX volunteermatching]$ http GET http://127.0.0.1:5000/api/users "Authorization: Bearer aOUfpaYJ7G9z2qVJ+x+cTu9rudU61ulr"
HTTP/1.0 200 OK
Content-Length: 343
Content-Type: application/json
Date: Wed, 15 May 2019 01:07:45 GMT
Server: Werkzeug/0.15.2 Python/3.6.8

{
    "_links": {
        "next": null,
        "prev": null,
        "self": "/api/partners?page=1&per_page=10&include_email=False"
    },
    "_meta": {
        "page": 1,
        "per_page": 10,
        "total_items": 1,
        "total_pages": 1
    },
    "items": [
        {
            "id": 1,
            "roles": [
                "Admin"
            ],
            "username": "admin"
        }
    ]
}

```
FYI, the token currently expires in 60 minutes after being generated. Try hitting /api/token/auth again to see if it returns a new token. If so, try the new token at /api/users. With the JWT setup I had better handling of the token expiring. I'll have to put back the better error response and the configuration variable to set the expiration time.

**Comment by Alex-Cannon** [comment]
I'll test this again tomorrow morning. My JWT/ajax request may have been bad. I'll get back to you.

**Comment by Alex-Cannon** [comment]
This was a simple syntax error with axios. I fixed it in my /react branch. Closing this issue.
