### ISSUE TITLE
Feature: Handle expired JWT tokens

### ISSUE THREAD

**Issue by Alex-Cannon** [CodeForFoco/volunteercore#63]
From what I understand, currently our JWT tokens expire after 1 hour. It would be nice if we had a refresh token on the front-end to handle expired tokens.

**Comment by stevenabadie** [comment]
This will take some reworking of most of the api. I'm going to hold off on doing this until after the MVP release and focus on getting unit testing in place.

**Comment by stevenabadie** [comment]
Closing this as duplicate topic of the newly created ticket #138
