### ISSUE TITLE
Feature: Use History API on front-end to handle redirects.

### ISSUE THREAD

**Issue by Alex-Cannon** [CodeForFoco/volunteercore#64]
Use cases:

1. I log out. I _should_ be redirected to the index page.
2. I sign in. I _should_ be redirected to the dashboard.
3. I go to "/" on my initial visit, I should be redirected to dashboard IF I have a JWT.

**Comment by Alex-Cannon** [comment]
Requests can be redirected with JS by forcing an HTTP request, but it takes longer than forcing react to swap pages.

**Comment by stevenabadie** [comment]
@Alex-Cannon I was going to make a separate ticket for UI/UX to request a redirect to either the /opportunities page or dashboard when signing in but this ticket covers the topic. Where the redirect goes is dependent on our decision on #113.

**Comment by Alex-Cannon** [comment]
@stevenabadie Let's do #113 your way. In that case, we can redirect users to /opportunities. I think even the admin will rarely CRUD tags and users, so even they should be redirected.

We can do it this way for the MVP. We can easily change this later.
