### ISSUE TITLE
Bug: Tag Category tags returned as array of unique letters, not array of tags.

### ISSUE THREAD

**Issue by Alex-Cannon** [CodeForFoco/volunteercore#67]
This goes back to the issue of VOA storing tags in a very strange way. We really should just have a flat data structure for tags, not a weird category system. I don't think we can move forward with this without contacting VOA.

**Comment by stevenabadie** [comment]
This should probably be split into two separate issues. I've separated out the concern in the description to #72.

It looks like you're seeing an issue with the /api/tag_categories endpoint but not certain per your description. If I make a GET request to /api/tag_categories I get the full string of each tag per tag_category: https://gist.github.com/stevenabadie/fa388e5f403f163d758472225fe54e41 . If that is the end point you are seeing this issue with, the api appears to be returning the full string AFAICT.

**Comment by Alex-Cannon** [comment]
This may have to do with the fact that the tags are stored in a string text field on the front-end. Let me test this to make sure it isn't the front-end with this issue.

**Comment by Alex-Cannon** [comment]
Confirmed front-end issue. Fixing now...

**Comment by Alex-Cannon** [comment]
At this point, I really need to re-structure the front-end. It's a bit of a mess when it comes to these forms. I'll restructure everything before doing this.

**Comment by Alex-Cannon** [comment]
Waiting on #83 to be resolved before I can continue.
