### ISSUE TITLE
Bug: 400 Error when 2 organizations have an opportunity with the same name.

### ISSUE THREAD

**Issue by Alex-Cannon** [CodeForFoco/volunteercore#71]
Test Case:
Organization A has an opportunity with { name: "code" }.
Organization B tries to add an opportunity with { name: "code" }
Organization B gets 400 "opportunity already exists" error

What if two organizations have the same opportunity? We should cover this case in our api. :)

**Comment by stevenabadie** [comment]
The opportunity name field is set to unique. I'll get that changed.
