### ISSUE TITLE
Should opportunity characterization be in a single tag model or separate categories

### ISSUE THREAD

**Issue by stevenabadie** [CodeForFoco/volunteercore#72]
Separated this out from #67 
> This goes back to the issue of VOA storing tags in a very strange way. We really should just have a flat data structure for tags, not a weird category system. I don't think we can move forward with this without contacting VOA.

**Comment by stevenabadie** [comment]
VOA's data is not stored in tags. It is stored in three separate models: skills, passions, and age group interest. I chose to make more generic TagCategory and Tag model to allow VOA or other users to define custom tag categories.

The original request was to be able to filter opportunities separately by each category. There are also duplicate items across some categories that do not necessarily mean the same thing. If we merge this to one model we'll need to discuss this with VOA but I agree it would make the new system simpler in the future.

**Comment by Alex-Cannon** [comment]
I agree. I think we should talk to Andrew about this and then move forward.

**Comment by Alex-Cannon** [comment]
For now, I'll close this issue. If Andrew brings it up and wants to change it, we can make a new issue.
