### ISSUE TITLE
Production: Setup Server for production

### ISSUE THREAD

**Issue by Alex-Cannon** [CodeForFoco/volunteercore#89]
We need to figure out how to setup the server for production.

The API works right now, as far as I know.
I do not think the python server handles serving the front-end right now.

We need to set this up. Create React App spits out ALL production files to /public that can be served.

**Comment by stevenabadie** [comment]
The api currently has a rough Heroku config using gunicorn which is working at Heroku. However, the config is not setting a few production things that should be turned on, like turning off debug mode.

**Comment by Alex-Cannon** [comment]
I know on heroku you can set environment variables in the settings tab of your site. This could potentially turn off debug mode?

For example, process.env.PRODUCTION === true ?
and so on

**Regarding the front-end, Create React App outputs a public folder that you can serve. Create React App does NOT handle production. You must use the public folder it outputs.**

To build the front-end run these commands:
* $ npm run build
    * Builds the front-end. Compresses & outputs minified files to /public. Serve the public folder and index.html in public to make create react app run.

[See the Create React App docs](https://facebook.github.io/create-react-app/docs/deployment) for deployment options.
