### ISSUE TITLE
UI/UX: How should users submit issues?

### ISSUE THREAD

**Issue by Alex-Cannon** [CodeForFoco/volunteercore#92]
Let's say that a user is having trouble modifying a certain field or they find an issue we didn't catch. How should they submit these issues?

I'd like to not be the guy to manage the server. Let's define a way they can submit issues.

Here is a suggestion:
Put a "Have an issue?" Link in the help page.
"Have an issue?
Volunteer Force is open source. **Click here** to submit an issue and we will get to it as soon as we can."

**Comment by stevenabadie** [comment]
@Alex-Cannon I think your suggestion makes sense. Just point them to the issue board here on github and have them make an issue ticket.

**Comment by Alex-Cannon** [comment]
Sweet. In that case, I'll rename this issue and create a quick help page.
