### ISSUE TITLE
UI/UX: Add advanced form validation

### ISSUE THREAD

**Issue by Alex-Cannon** [CodeForFoco/volunteercore#95]
It'd be nice if fields were more controlled. For example, right now you can add a 55555555555 number as a zip code. Fields like these we should control.

*EDIT*
After Reviewing our codebase and talking with @JarethRader, I've decided we need to refactor some code before this can be done. Things are a bit of a mess right now. I'll link to a pic on how our forms should be structured:

[Checkout this diagram](https://codeforfoco.slack.com/files/UH99K34DR/FKV6L812N/img_0743.jpg)

**Comment by JarethRader** [comment]
This should be easy to do with some regex. I can get on it.

**Comment by Alex-Cannon** [comment]
@JarethRader awesome. Like I said in the slack, pages/opportunities uses /utils/endpoints to generate the forms. /utils/endpoints is where you should put the test functions, which should integrate with the /objects input components.

If you want more detail, let me know!

**Comment by Alex-Cannon** [comment]
@JarethRader I think at this point, I'm going to avoid refactoring code. In the future, I should take time to do better planning to make the code more DRY, readable, and testable. I'm excited for my next project, where I can better practice these ideas. Not sure what it will be though!

Anyway, regarding advanced form validation, I think the best thing to do is for you to go ahead and give it your best shot if you like. Make it work for 1 component, then have steven or I review it. If it looks good, we'll roll with it.

**Comment by Alex-Cannon** [comment]
This will be added in #177. Closing now.
